### ISSUE TITLE
Is there a way to customize the style of the popup Like changing the font family and layout of the popup content?

### ISSUE THREAD

**Issue by Mohid123456** [jaganbishoyi/ngx-password-validator#32]

**Comment by jaganbishoyi** [comment]
Hi @Mohid123456 ,
We can customize the style of the popup using the popup class ( .popup ). And we need to use ng-deep.

`::ng-deep {
    .popup {
        .popup-window {
            .heading {
                color: red !important;
                font-family: cursive;
            }
        }
    }
}`
