### ISSUE TITLE
Random error from few days.

### ISSUE THREAD

**Issue by spolsani-vainc** [jaganbishoyi/ngx-password-validator#38]
From last few days, I am receiving below error randomly. It worked fine when I removed default options but they are back after nom install

Can't resolve all parameters for NgPasswordValidatorComponent: (?, ?, ?).

**Comment by jaganbishoyi** [comment]
> From last few days, I am receiving below error randomly. It worked fine when I removed default options but they are back after nom install
> 
> 
> 
> Can't resolve all parameters for NgPasswordValidatorComponent: (?, ?, ?).

Hi please install latest version.
The issue has been resolved 🙂
